In [1]:
import numpy as np

### Creating Arrays , Array Type and Shape

In [2]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
arr2 = arr1.reshape(1,6)
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]]
(1, 6)


### Creating 2D Arrays Directly

In [4]:
arr2 = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
print(arr2)
print(type(arr2))

arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
print(type(arr2))

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
<class 'list'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
<class 'numpy.ndarray'>


### Using Inbuilt Functions to Create Arrays

In [5]:
arr = np.arange(0,10,2)
print(arr)
arr_reshaped = arr.reshape(5, 1)
print(arr_reshaped)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [6]:
ones_arr = np.ones((13,14))
print(ones_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
ones_arr = np.zeros((13,14))
print(ones_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Array Attributes

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [8, 9, 10]])
print("-"*30)
print("Array : \n",arr)
print("-"*30)
print("Shape :",arr.shape)
print("-"*30)
print("Number of dimensions:",arr.ndim)
print("-"*30)
print("Size (Number of elements)",arr.size)
print("-"*30)
print("Data Type:",arr.dtype)
print("-"*30)
print("Item Size: (in bytes)",arr.itemsize)

------------------------------
Array : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
------------------------------
Shape : (3, 3)
------------------------------
Number of dimensions: 2
------------------------------
Size (Number of elements) 9
------------------------------
Data Type: int64
------------------------------
Item Size: (in bytes) 8


### Vectorized Operations

In [10]:
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,3,5,7,9])
print("Additon:",arr1 + arr2)
print("-"*65)
print("Substraction:",arr1 - arr2)
print("-"*65)
print("Multiplication:",arr1 * arr2)
print("-"*65)
print("Division",arr1 / arr2)

Additon: [ 3  7 11 15 19]
-----------------------------------------------------------------
Substraction: [1 1 1 1 1]
-----------------------------------------------------------------
Multiplication: [ 2 12 30 56 90]
-----------------------------------------------------------------
Division [2.         1.33333333 1.2        1.14285714 1.11111111]


### Universal Functions

In [11]:
arr = np.arange(1,7)
print(arr)
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1 2 3 4 5 6]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing

In [12]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0,1])

2


In [14]:
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [15]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [17]:
print(arr)
print(arr[1:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [18]:
print(arr[0:3,0:1])

[[1]
 [5]
 [9]]


In [19]:
## Modify
arr[0][0] = 10
print(arr)

[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr[1:]=100
print(arr)

[[ 10   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Statistical Operations and Normalization

In [21]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.5
5.5
2.8722813232690143
8.25


### Logical Operations

In [23]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]


In [24]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [25]:
print(arr[4:]) 

[5 6 7]


In [26]:
print(arr[:4])

[1 2 3 4]


In [27]:
print(arr[-4:-1])

[4 5 6]


In [28]:
print(arr[1:6:2])

[2 4 6]


In [29]:
print(arr[::2])

[1 3 5 7]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("2-D array :\n",arr)
print(arr[1, 1:4])

2-D array :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [31]:
import numpy as np

# Create an array of numbers from 0 to 19
# and reshape it into a 4x4 grid
arr = np.arange(20).reshape(4, 5)

print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
row_1_and_2 = arr[1:3]
print(row_1_and_2)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
cols_1_and_2 = arr[:,1:3]
print(cols_1_and_2)

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [34]:
sub_matrix = arr[1:3, 2:4]
print(sub_matrix)

[[ 7  8]
 [12 13]]
